@echo off
echo Stopping existing processes...
taskkill /F /IM dotnet.exe >nul 2>&1

echo Building project...
dotnet build

echo Compiling CSS...
tailwindcss.exe --input wwwroot/css/input.css --output wwwroot/css/tailwind.css --minify

echo Starting server...
dotnet run
